# Generated by Django 3.1.1 on 2020-12-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inet_speed', models.IntegerField(verbose_name='Internet speed')),
                ('inet_limit', models.BigIntegerField(verbose_name='Internet limit')),
                ('sms', models.IntegerField()),
                ('calls', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
