# Generated by Django 3.1.1 on 2020-12-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='decsription',
            new_name='description',
        ),
    ]
