# Generated by Django 3.1.1 on 2020-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20201204_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='additional_services',
            field=models.CharField(default='', max_length=100),
        ),
    ]
