# Generated by Django 3.1.1 on 2020-12-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20201211_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='сard',
        ),
    ]
