# Generated by Django 3.1.1 on 2020-12-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_remove_customer_сard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='firstapp.card'),
        ),
    ]
