# Generated by Django 3.1.1 on 2020-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_customer_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='sms',
        ),
        migrations.AlterField(
            model_name='card',
            name='date_of_create',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='number_card',
            field=models.CharField(max_length=19),
        ),
    ]
